### PR TITLE
Update to support orchestration

### PR DESCRIPTION
**Pull request by ryanwi**
- [x] log to STDOUT
- [x] Support JSON formatted logs
- [ ] ~readiness/liveness checks~ working for now, using the web status endpoints
- [ ] ~orchestrator will control process, remove daemon capabilty~ supports both daemonized and non-daemonized already

### CODE REVIEW

**Review by phanyzewski — COMMENTED** [review]
In the runner.rb we're setting a default of false, but in core.rb we have a default of true.

```ruby
# runner.rb
 .initialize_logger(daemonized: options.fetch(:daemon) { false })
```

```ruby
# core.rb
def initialize_logger(daemonized: true)
```

Is that intentional?

Otherwise 👍

**Review by rebelpacket — APPROVED** [review]
🚀  Just duplicated this for dozer;  Nice work supporting both!!

**Comment by ryanwi** [comment]
Updated the default to false, that is a good catch. It was kind of intentional, to keep the legacy deploys defaulting to demonized , but confusing when I think about it again. There are 3 places where that has a default, so better to be consistent.

**Review by phanyzewski — APPROVED** [review]
Thanks for clearing up the defaults!  I figured the intention was for this to not be a breaking change 🚢 🇮🇹

**Pull request merged**
