### PR TITLE
Retries enabled errors when they fail in the worker.

### PR DESCRIPTION
**Pull request by randy-girard**

### CODE REVIEW

**Comment by randy-girard** [comment]
Any thoughts as to why we didn't do this, or perhaps it was just missed. This is in the delayed worker

**Comment by knappe** [comment]
@randy-girard Is this meant to be in supplement to https://github.com/emque/emque-consuming#automatic-error-retries?

**Comment by randy-girard** [comment]
@knappe Yes. Seems we only do it for delayed messages

**Comment by ryanwi** [comment]
What's the goal here?

**Comment by ryanwi** [comment]
rather, what's the problem this is intended to solve?

**Comment by ryanwi** [comment]
This would mean immediate retry rather than a backoff, of any error which was not in the original design I believe?

**Comment by randy-girard** [comment]
Talked to tyler. Going to make a change in the am to just log errors so we can see whats going on

**Pull request closed without merging**
